In [1]:
"""
Exercise 4: NumPy Array Operations
Complete the following tasks using NumPy.
"""

'\nExercise 4: NumPy Array Operations\nComplete the following tasks using NumPy.\n'

In [2]:
import numpy as np

# Task 1: Create a 5x5 matrix where border elements are 1 and interior is 0

# Create matrix
matrix55 = np.zeros((5, 5))

# Now make border items 1
matrix55[:, 0] = 1
matrix55[:, -1] = 1

print(matrix55)

[[1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]]


In [3]:
# Task 2: Normalize a random array

# Each col having mean = 0 & std = 1 by default
np.random.seed(42)
randArr = np.random.randn(100, 3)
print(randArr)


[[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733]
 [-0.90802408 -1.4123037   1.46564877]
 [-0.2257763   0.0675282  -1.42474819]
 [-0.54438272  0.11092259 -1.15099358]
 [ 0.37569802 -0.60063869 -0.29169375]
 [-0.60170661  1.85227818 -0.01349722]
 [-1.05771093  0.82254491 -1.22084365]
 [ 0.2088636  -1.95967012 -1.32818605]
 [ 0.19686124  0.73846658  0.17136828]
 [-0.11564828 -0.3011037  -1.47852199]
 [-0.71984421 -0.46063877  1.05712223]
 [ 0.34361829 -1.76304016  0.32408397]
 [-0.38508228 -0.676922    0.61167629]
 [ 1.03099952  0.93128012 -0.83921752]
 [-0.30921238  0.33126343  0.97554513]
 [-0.47917424 -0.18565898 -1.10633497]
 [-1.19620662  0.81252582  1.35624003]
 [-0.07201012  1.0035329   0.36163603]
 [-0.64511975  0.36139561  1.53803657]
 [-0.03582604  1.56464366 -2.6197451 ]
 [ 0.8219025   0.08704707

In [4]:
# Task 3: Implement linear regression solution using normal equation

X = np.random.randn(50, 3)
true_theta = np.array([2.5, -1.2, 3.7])
y = X @ true_theta + np.random.randn(50) * 0.1

# Normal eqn (theta = (X^T X)^(-1) X^T y) translated:
theta_hat = np.linalg.inv((np.transpose(X) @ X)) @ (np.transpose(X) @ y)

print(f"True Theta: ", true_theta)
print(f"Theta hat: ", theta_hat)


True Theta:  [ 2.5 -1.2  3.7]
Theta hat:  [ 2.51723721 -1.19783796  3.72399266]


In [5]:
"""
Exercise 5: Pandas Data Analysis
Analyze a dataset of student performance.
"""

import pandas as pd
import numpy as np

# Create sample dataset
np.random.seed(42)
n_students = 200

data = {
    'student_id': range(1000, 1000 + n_students),
    'major': np.random.choice(['CS', 'Math', 'Physics', 'Biology'], n_students),
    'year': np.random.choice([1, 2, 3, 4], n_students),
    'exam_score': np.random.normal(75, 10, n_students).clip(0, 100),
    'assignments_completed': np.random.randint(0, 11, n_students),
    'hours_studied': np.random.normal(15, 5, n_students).clip(1, 40)
}

df = pd.DataFrame(data)

# Introduce some NaN values
df.loc[np.random.choice(n_students, 10), 'exam_score'] = np.nan
df.loc[np.random.choice(n_students, 5), 'hours_studied'] = np.nan

In [9]:
# Display basic information about the dataset
# print(df.describe())

# Identify and count missing values
missingValsCount = df.isnull().sum().sum()
print(f"Total missing values in data frame: ", missingValsCount)

# Fill missing exam_score with the mean score for the student's major
df_stats = df.groupby('major')['exam_score'].agg(['mean'])

for index, row in df[df['exam_score'].isnull()].iterrows():
    major = row['major']
    mean_for_major = df_stats.loc[major, 'mean']
    df.loc[index, 'exam_score'] = mean_for_major


# Fill missing hours_studied with the median for the student's year
df_stats2 = df.groupby('year')['hours_studied'].agg(['median'])
df_nulls2 = df[df['hours_studied'].isnull()]


for index, row in df[df['hours_studied'].isnull()].iterrows():
    year = row['year']
    median_for_year = df_stats2.loc[year, 'median']
    df.loc[index, 'hours_studied'] = median_for_year



# Create new 'performance' column
# 'Excellent' (>90), 'Good' (80-90), 'Average' (70-80), 'Needs Improvement' (<70)

df['Performance'] = np.where(df['exam_score'] > 90, 'Excellent',
                    np.where((df['exam_score'] >= 80) & (df['exam_score'] < 90), 'Good',
                    np.where((df['exam_score'] >= 70) & (df['exam_score'] < 80), 'Average', 'Needs Improvement')))

Total missing values in data frame:  0
